version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8090:8090"
    networks:
      - tasksandnews-network
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tasksandnews
      POSTGRES_USER: tasksandnewsAdmin
      POSTGRES_PASSWORD: tasksandnewsAdmin
    ports:
      - "5432:5432"
    networks:
      - tasksandnews-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  tasksandnews-network:
    driver: bridge

volumes:
  postgres-data:
